# Numpy Arrays

In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
misturados = [2.9, 3, 'none', False]

In [4]:
for el in misturados:
    print(type(el))

<class 'float'>
<class 'int'>
<class 'str'>
<class 'bool'>


In [6]:
misturados_array = np.array(misturados)

In [7]:
misturados_array

array(['2.9', '3', 'none', 'False'], dtype='<U32')

In [10]:
for el in misturados_array:
    print(type(el))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Numpy Array (Operações Inteligentes)

In [1]:
import numpy as np

In [2]:
lista = [1, 2, 3, 4, 5]

In [6]:
array = np.array(lista)

In [9]:
array * 2

array([ 2,  4,  6,  8, 10])

In [8]:
lista * 2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

# Numpy Array (Indexando e Cortando _'Slicing'_)

In [1]:
import numpy as np

In [3]:
lista = np.arange(0,11)

In [4]:
lista[1]

1

In [5]:
lista[1:10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
lista[-1]

10

In [10]:
lista[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
lista[:5]

array([0, 1, 2, 3, 4])

In [12]:
lista[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
lista[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# Numpy Array (Multiplas Dimensões)

In [14]:
import numpy as np

In [17]:
lista02 = np.arange(1,13)
lista02

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
lista02.shape

(12,)

In [19]:
lista02.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [20]:
lista02.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [30]:
lista02.reshape(2,6)*10

array([[ 10,  20,  30,  40,  50,  60],
       [ 70,  80,  90, 100, 110, 120]])

In [32]:
lista02

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Numpy Array e Boolean

In [33]:
import numpy as np

In [34]:
array = np.arange(11)

In [36]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
cond = array >= 5
cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

# Numpy e Números Aleatórios

In [39]:
import numpy as np

In [52]:
array = np.random.randint(1, 100, 20)
array

array([69, 50, 56, 68,  3, 85, 40, 67, 85, 48, 62, 49,  8, 93, 53, 98, 86,
       95, 28, 35])